---
kind: pipeline
name: default

steps:
  - name: build
    image: hukuruio/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: source
        path: /opt/src/app
    commands:
      - make

  - name: cleanup
    image: hukuruio/docker-compose 
    commands:
      - make cleanup
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      status:
      - success
      - failure

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: source
    path: /drone/src
    
