---
kind: pipeline
name: default

steps:
  - name: build
    image: hukuruio/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - make

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
