---
kind: pipeline
name: default

steps:
  - name: build
    image: hukuruio/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - make release

  - name: test
    image: hukuruio/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker exec users pipenv install --dev
      - make test     


  - name: cleanup
    image: hukuruio/docker-compose 
    commands:
      - make cleanup
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      status:
      - success
      - failure

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
