version: '3.7'

services:

  users:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: users:release
    container_name: users
    ports:
      - 5002:8765
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://apps:apps_pass@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgresql://apps:apps_pass@users-db:5432/users_test
      - PORT=8765
    depends_on:
      - users-db

  users-db:
    build:
      context: ./src/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=apps
      - POSTGRES_PASSWORD=apps_pass
