version: '3.7'

services:

  users:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "/opt/src/app/start.sh"]
    container_name: users
    volumes:
      - ./src:/opt/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://apps:apps_pass@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://apps:apps_pass@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    build:
      context: ./src/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=apps
      - POSTGRES_PASSWORD=apps_pass
